language: csharp

solution: CodilityPractice.sln

install:
  - nuget restore CodilityPractice.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release CodilityPractice.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./Equi.Tests/bin/Release/Equi.Tests.dll
